name: CI

on:
  workflow_dispatch: # Allows manual trigger of the workflow from GitHub UI
  pull_request:      # Triggers workflow on pull requests
    branches:        # Only for PRs targeting these branches
      - main
      - master
  push:              # Triggers workflow on push events
    branches:        # Only for pushes to these branches
      - main
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --immutable

      - name: Run ESLint
        run: npm run lint
